#!/usr/bin/env python3
"""
Bundle every stories/*.json into simulator/stories.js so the simulator can be
opened straight from disk (file://) without a web server or fetch().

Usage:
    python tools/build_stories_js.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STORIES = ROOT / "stories"
OUT = ROOT / "simulator" / "stories.js"

books = []
for p in sorted(STORIES.glob("*.json")):
    with open(p, encoding="utf-8") as f:
        book = json.load(f)
    book.setdefault("meta", {})["file"] = p.name
    books.append(book)

# Put the hand-written lighthouse first if present, it is the reference book.
def title_of(b):
    t = b["meta"].get("title", "")
    return (t.get("en") or next(iter(t.values()), "")) if isinstance(t, dict) else t


books.sort(key=lambda b: (b["meta"].get("file") != "hollow_lighthouse.json", b["meta"].get("file", "").startswith("gen_"), b["meta"].get("tier", 1), title_of(b)))

OUT.write_text(
    "// Generated by tools/build_stories_js.py. Do not edit, edit stories/*.json instead.\n"
    "window.MOVENTURE_STORIES = " + json.dumps(books, indent=1, ensure_ascii=False) + ";\n",
    encoding="utf-8",
)
print(f"wrote {OUT.relative_to(ROOT)} with {len(books)} book(s): " + ", ".join(title_of(b) for b in books))
